# Uncomment the next line to define a global platform for your project
platform :ios, '15.7'

target 'swiftUIChatter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftChatter
  pod 'GoogleMaps'
	pod 'GooglePlaces'

end