
CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    YEAR_OF_BIRTH INT,
    MONTH_OF_BIRTH INT,
    DAY_OF_BIRTH INT,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CHARGING_SINCE INT NOT NULL, --EXTRACT(YEAR FROM NOW())
    DESCRIPTION VARCHAR(1000) NOT NULL,
    IMAGE_URL VARCHAR(1000)
);

CREATE TABLE CHARGERS (
    CID SERIAL NOT NULL,
    USER_ID INT NOT NULL UNIQUE REFERENCES USERS(USER_ID),
    AVAILABLE VARCHAR(100) NOT NULL, 
    START_TIME_AVAILABILITY TIME NOT NULL,
    END_TIME_AVAILABILITY TIME NOT NULL,
    CHARGER_TYPE VARCHAR(100) NOT NULL,
    PRICE DECIMAL NOT NULL,
    STREET_ADDRESS VARCHAR(100) NOT NULL,
    CITY_ADDRESS VARCHAR(100) NOT NULL, 
    STATE_ADDRESS VARCHAR(100) NOT NULL,
    ZIPCODE_ADDRESS VARCHAR(100) NOT NULL,
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
    PRIMARY KEY (CID), 
    CHECK(PRICE >= 0),
    CHECK(AVAILABLE = 'TRUE' OR AVAILABLE = 'FALSE'),
    CHECK(START_TIME_AVAILABILITY <= END_TIME_AVAILABILITY)

);


CREATE TABLE CHARGES_AT (
    PRIMARY KEY(USER_ID, CID),
    USER_ID INT NOT NULL REFERENCES USERS(USER_ID),
    CID INT NOT NULL REFERENCES CHARGERS(CID),
    START_TIME TIME NOT NULL

);

CREATE TABLE ADD_CHARGER(
    PRIMARY KEY(USER_ID, CID),
    USER_ID INT NOT NULL REFERENCES USERS(USER_ID),
    CID INT NOT NULL REFERENCES CHARGERS(CID)
);

CREATE TABLE REVIEWS(
    REVIEW_ID SERIAL PRIMARY KEY,
    REVIEW_DATE VARCHAR(20) NOT NULL, 
    STARS DECIMAL NOT NULL,
    SUBJECT VARCHAR(150) NOT NULL,
    MESSAGE VARCHAR(900) NOT NULL, 
    RECEIVING_REVIEW_TYPE VARCHAR(100) NOT NULL,
    HOST_ID INTEGER NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    DRIVER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CHECK (STARS >= 0 AND STARS <= 5),
    CHECK (RECEIVING_REVIEW_TYPE = 'DRIVER' OR RECEIVING_REVIEW_TYPE = 'HOST')
);

CREATE TABLE VEHICLE(
    USER_ID INT REFERENCES USERS(USER_ID),
    LICS_NUMBER VARCHAR NOT NULL,
    MODEL VARCHAR(100),
    COLOR VARCHAR(100),
    PRIMARY KEY(LICS_NUMBER)
);

CREATE TABLE DRIVES(
    LICS_NUMBER VARCHAR NOT NULL REFERENCES VEHICLE(LICS_NUMBER) ON DELETE CASCADE,
    DRIVER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (LICS_NUMBER, DRIVER_ID)
);

CREATE TABLE PHOTOS(
    PHOTO_ID SERIAL,
    IMG_URL TEXT NOT NULL,
    CID INTEGER NOT NULL REFERENCES CHARGERS(CID),
    PRIMARY KEY (PHOTO_ID)
);

CREATE TABLE REQUEST(
    USER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID),
    CID INTEGER NOT NULL REFERENCES CHARGERS(CID),
    HOST_ID INTEGER NOT NULL REFERENCES USERS(USER_ID)
);

CREATE TABLE ACTIVITY(
    HOST_ID INTEGER NOT NULL REFERENCES USERS(USER_ID),
    DRIVER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID),
    DURATION VARCHAR(100) NOT NULL,
    COST VARCHAR(100) NOT NULL
);

GRANT ALL PRIVILEGES ON DATABASE chargevrywhere TO devteam;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO devteam;

GRANT USAGE, SELECT ON SEQUENCE users_user_id_seq TO devteam;
GRANT USAGE, SELECT ON SEQUENCE chargers_cid_seq TO devteam;
GRANT USAGE, SELECT ON SEQUENCE reviews_review_id_seq TO devteam;
GRANT USAGE, SELECT ON SEQUENCE photos_photo_id_seq TO devteam;
