INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION, IMAGE_URL)
VALUES('Branden', 'Mayday', 2000, 10, 28, 'bmayday', 'password1234', EXTRACT(YEAR FROM NOW()), 'I am Branden Mayday. I drive a car.', 'https://18.225.8.255/media/541670287054.7138658.jpeg');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(1, 'ABC124', 'Camry', 'Turqiouse');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC124', 1);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION, IMAGE_URL)
VALUES('Allison', 'Kwang', 2000, 10, 28, 'akkwang', 'password12345', EXTRACT(YEAR FROM NOW()), 'I am Allison Kwang. I have a charger.', 'https://18.225.8.255/media/541670287054.7138658.jpeg');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(2, 'ABC125', 'Leaf', 'Blue');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC125', 2);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Tyler', 'Schneider', 2000, 10, 24, 'schneity', 'password123456', EXTRACT(YEAR FROM NOW()), 'I am first last. I drive a car.');
INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(3, 'ABC126', 'Town&Country', 'White');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC126', 3);

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(3, 'ABC127', 'Town&Country', 'White');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC127', 3);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Varindra', 'Persad Maharaj', 2000, 06, 08, 'varindra', 'password123456', EXTRACT(YEAR FROM NOW()), 'I am Varindra Persad Maharaj. I drive a car.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(4, 'ABC128', 'Sentra', 'Green');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC128', 4);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('John', 'Oberlies', 2012, 07, 01, 'joberlies', 'password123456', EXTRACT(YEAR FROM NOW()), 'I am John Oberlies. I drive a car.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(5, 'ABC129', 'Charger', 'Red');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC129', 5);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Marcus', 'Li', 2001, 12, 21, 'marcusli', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I drive a car. It charges very fast');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(6, 'ABC130', 'Cube', 'Pink');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC130', 6);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Liam', 'Nymn', 1999, 12, 22, 'lnymn', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'Get a free water every time you charge!');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(7, 'ABC131', 'Civic', 'Brown');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC131', 7);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Peter', 'Parker', 1999, 12, 12, 'pparker', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Spiderman.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(8, 'ABC132', 'Civic', 'Blue');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC132', 8);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Bruce', 'Wayne', 1984, 06, 06, 'batman', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Batman.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(9, 'ABC133', 'Model 3', 'White');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC133', 9);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Mary', 'Mary', 1991, 02, 06, 'marysquared', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Mary. My house has all types of chargers!');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(10, 'ABC134', 'Model 2', 'Black');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC134', 10);

INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Mary', 'Yram', 1991, 02, 06, 'marybackwards', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Mary. I have a charger');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Chris', 'Christopher', 1981, 03, 10, 'marysquared', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Mary. I have 2 chargers!');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Keron', 'Walcott', 1987, 12, 05, 'kwalcott', 'randomAlphaNumericString', EXTRACT(YEAR FROM NOW()), 'I am Keron. We have a minifridge!');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Kyle', 'Joshua', 2000, 11, 18, 'kjosh', 'nsjiocds', EXTRACT(YEAR FROM NOW()), 'I am Kyle Joshua. random words.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(14, 'ABC135', 'fiesta', 'orange');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC124', 14);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Alan', 'Umraw', 1993, 12, 15, 'aUmraw', 'asdfghjk', EXTRACT(YEAR FROM NOW()), 'I am Alan Umraw.More random words.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(16, 'ABC136', 'prius', 'tan');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC124', 16);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Candice', 'Glasser', 1993, 01, 29, 'cglasser', 'asdfghjk', EXTRACT(YEAR FROM NOW()), 'I am Candice Glasser.Even more random words.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(17, 'ABC137', 'silverado', 'grey');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC137', 17);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Mary', 'Markley', 1843, 01, 20, 'mmarkley', 'asdfghjk', EXTRACT(YEAR FROM NOW()), 'I am Mary Markley. I have 2 dogs');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(18, 'ABC138', 'rav4', 'grey');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC137', 18);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Trevor', 'Sayers', 1993, 01, 13, 'tsayers', 'enriuvwa*(', EXTRACT(YEAR FROM NOW()), 'I am Trevor Sayers. I am a doctor.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(19, 'ABC139', 'sentra', 'white');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC137', 19);


INSERT INTO USERS (FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USERNAME, PASSWORD, CHARGING_SINCE, DESCRIPTION)
VALUES('Ronald', 'McDonald', 1893, 01, 25, 'rmcdonald', 'qwertyu', EXTRACT(YEAR FROM NOW()), 'I am Ronald McDonald. I amke burgers.');

INSERT INTO VEHICLE (USER_ID, LICS_NUMBER, MODEL, COLOR)
VALUES(20, 'ABC140', 'model3', 'green');

INSERT INTO DRIVES (LICS_NUMBER, DRIVER_ID)
VALUES('ABC140', 20);


INSERT INTO CHARGERS(AVAILABLE, USER_ID ,START_TIME_AVAILABILITY, END_TIME_AVAILABILITY, CHARGER_TYPE, PRICE, STREET_ADDRESS, CITY_ADDRESS, STATE_ADDRESS, ZIPCODE_ADDRESS, LATITUDE, LONGITUDE)
VALUES('TRUE', 1,'1999-01-08 04:05:06', '2023-01-08 04:05:06', '240 V', 0.55, '2505 Hayward Ave', 'Ann Arbor', 'MI', '48109', 42.2941502555369, -83.70977088280107);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 1);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 1);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 1);


INSERT INTO CHARGERS(AVAILABLE, USER_ID,START_TIME_AVAILABILITY, END_TIME_AVAILABILITY, CHARGER_TYPE, PRICE, STREET_ADDRESS, CITY_ADDRESS, STATE_ADDRESS, ZIPCODE_ADDRESS, LATITUDE, LONGITUDE)
VALUES('TRUE', 2,'1999-01-08 04:05:06', '2023-01-08 04:05:06', '120 V', 0.25, '500 West William St', 'Ann Arbor', 'MI', '48103', 42.277999361847876, -83.7535080269824);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 2);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 2);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 2);


INSERT INTO CHARGERS(AVAILABLE, USER_ID,START_TIME_AVAILABILITY, END_TIME_AVAILABILITY, CHARGER_TYPE, PRICE, STREET_ADDRESS, CITY_ADDRESS, STATE_ADDRESS, ZIPCODE_ADDRESS, LATITUDE, LONGITUDE)
VALUES('TRUE', 3,'1999-01-08 04:05:06', '2023-01-08 04:05:06', '1million V', 0.25, '500 West William St', 'Ann Arbor', 'MI', '48103', 42.277999361847876, -83.7535080269824);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 3);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 3);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 3);


INSERT INTO CHARGERS(AVAILABLE, USER_ID,START_TIME_AVAILABILITY, END_TIME_AVAILABILITY, CHARGER_TYPE, PRICE, STREET_ADDRESS, CITY_ADDRESS, STATE_ADDRESS, ZIPCODE_ADDRESS, LATITUDE, LONGITUDE)
VALUES('TRUE', 4,'1999-01-08 05:05:32', '2023-01-08 07:05:06', '1million V', 1.25, '650 S Forest St', 'Ann Arbor', 'MI', '48104', 42.27393, -83.73392);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 4);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 4);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 4);


INSERT INTO CHARGERS(AVAILABLE, USER_ID,START_TIME_AVAILABILITY, END_TIME_AVAILABILITY, CHARGER_TYPE, PRICE, STREET_ADDRESS, CITY_ADDRESS, STATE_ADDRESS, ZIPCODE_ADDRESS, LATITUDE, LONGITUDE)
VALUES('TRUE', 5,'2000-02-08 05:05:32', '2023-01-08 06:05:06', '240 V', 0.45, '650 S Forest St', 'Ann Arbor', 'MI', '48104', 42.27393, -83.73392);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 5);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 5);

INSERT INTO PHOTOS(IMG_URL, CID)
VALUES ('https://18.225.8.255/media/541670287054.7138658.jpeg', 5);


INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(1, '15', 5, 'sample subject', 'sample message', 'DRIVER', 1, 1);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(2, '15', 4.5, 'sample subject2', 'sample message2', 'DRIVER', 1, 1);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(3, '20', 4.1, 'sample subject3', 'sample message3', 'HOST', 1, 2);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(4, '22', 4, 'sample subject4', 'sample message4', 'HOST', 2, 3);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(5, '19', 4.6, 'sample subject5', 'sample message5', 'HOST', 2, 4);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(6, '20', 4.6, 'sample subject6', 'sample message6', 'HOST', 2, 5);

INSERT INTO REVIEWS(REVIEW_ID, REVIEW_DATE, STARS, SUBJECT, MESSAGE, RECEIVING_REVIEW_TYPE, HOST_ID, DRIVER_ID)
VALUES(7, '20', 4.6, 'sample subject8', 'sample message7', 'HOST', 2, 6);

--2 requests for the same charger
INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(1, 1, 1);

INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(2, 1, 1);

--1 User requests 2 chargers(same host)
INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(1, 1, 1);

INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(2, 2, 1);

--1 User requests 2 chargers(different hosts)
INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(1, 2, 1);

INSERT INTO REQUEST(USER_ID, CID, HOST_ID)
VALUES(2, 3, 2);

--Using standard date format yyyy-MM-dd HH:mm:ss
INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (1, 1, '2022-12-01 13:32:59');

--Same user charges on 2 days
INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (1, 1, '2022-12-02 15:42:59');

--User charges with 2 chargers on the same day(eg a roadtrip)
INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (1, 2, '2022-12-02 18:42:59');

INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (2, 3, '2022-12-02 11:42:59');

INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (4, 2, '2022-12-02 12:42:59');

--Popular charger
INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (2, 1, '2022-12-02 12:42:59');

INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (3, 1, '2022-12-02 13:42:59');

INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (4, 1, '2022-12-02 14:42:59');

INSERT INTO CHARGES_AT(USER_ID, CID, START_TIME)
VALUES (5, 1, '2022-12-02 15:42:59');

